### install packages
install.packages('lmtest')
install.packages('DBI')
install.packages('kableExtra')
install.packages('tidyverse')
install.packages('stargazer')
install.packages('plm')
install.packages('lubridate')
install.packages('mlbench')
install.packages('readr')
install.packages('ggplot2')
install.packages('MASS')
install.packages("broom")
install.packages("ggpubr")

### Load libraries
library(tidyverse)
library(DBI)
library(kableExtra)
library(stargazer)
library(plm)
library(lubridate)
library(mlbench)
library(readr)
library(ggplot2)
library(MASS)
library(broom)
library(ggpubr)
library(readxl)